main:
	aarch64-linux-gnu-gcc   *.cc  -o main   --sysroot=/opt/rk1808-sdk/buildroot/output/rockchip_rk1808/host/aarch64-buildroot-linux-gnu/sysroot -I./rockx-rk1808-Linux/include   -L./rockx-rk1808-Linux/lib64  -lrockx    -L./  -lDRMwrap  -ldrm  -lpthread
clean:
	rm main
